piece1 = Piece.create(title: "Writing Code with Carrots", style: "documentary", subject: "coding", medium: "polaroid", size: "20 x 20" , price: 9.99, artist_id: 1, exhibition_id: 1)
piece2 = Piece.create(title: "Clown Juice", style: "classic", subject: "substance abuse", medium: "canvas", size: "24 x 42" , price: 25.00, artist_id: 2, exhibition_id: 2)
piece3 = Piece.create(title: "Bingo", style: "figurative", subject: "pets", medium: "pottery", size: "608 x 2015" , price: 90.00, artist_id: 3, exhibition_id: 3)
piece4 = Piece.create(title: "Watching Television with Beer", style: "Fine Art", subject: "nude", medium: "C-type", size: "2 x 2" , price: 80.00, artist_id: 4, exhibition_id: 4)
piece5 = Piece.create(title: "Blowing Things Up", style: "graffiti", subject: "Arizona", medium: "desert rocks", size: "20 x 60" , price: 99.99, artist_id: 5, exhibition_id: 5)

artist1 = Artist.create(name: "Ethan Steiner" , location: "New York City", bio: "bio goes here", piece_id: 1, exhibition_id: 1)
artist2 = Artist.create(name: "Johnny Scheuch" , location: "New York City", bio: "bio goes here", piece_id: 2, exhibition_id: 2)
artist3 = Artist.create(name: "Chris Bradshaw" , location: "New York City", bio: "bio goes here", piece_id: 3, exhibition_id: 3)
artist4 = Artist.create(name: "Linda Haviv" , location: "New York City", bio: "bio goes here", piece_id: 4, exhibition_id: 4)
artist5 = Artist.create(name: "Alex the cat" , location: "Mexico", bio: "bio goes here", piece_id: 5, exhibition_id: 5)

exhibition1 = Exhibition.create(location: "New York, NY", piece_id: 1, artist_id: 1)
exhibition2 = Exhibition.create(location: "Newark, NJ", piece_id: 2, artist_id: 2)
exhibition3 = Exhibition.create(location: "Caracas, Venezuela", piece_id: 3, artist_id: 3)
exhibition4 = Exhibition.create(location: "San Pedro Sula, Honduras", piece_id: 4, artist_id: 4)
exhibition5 = Exhibition.create(location: "Acapulco, Mexico", piece_id: 5, artist_id: 5)
